services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8086:8086"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=authentication_service;Username=electi;Password=536051;Port=5432;Pooling=true;
      - ASPNETCORE_URLS=http://+:8086
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: authentication_service
      POSTGRES_USER: electi
      POSTGRES_PASSWORD: 536051
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U electi -d authentication_service" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  app-network:
